### PR TITLE
Added missing favicon.ico

### PR DESCRIPTION
**Pull request by mskurnik**
Added the missing `favicon.ico` file from HTML folder so there is an icon for the browser to render.

### CODE REVIEW

**Comment by mutability** [comment]
This should be OK for 8080 but won't work for port 80. I guess we'd want one in `piaware-web` for sdcard images too.

**Comment by mutability** [comment]
Or I guess a `<link rel>` in index.html (not tested)

**Comment by marcelstoer** [comment]
I was just about the implement the same fix. Any chances of this getting eventually merged?

> This should be OK for 8080 but won't work for port 80. 

Why? Can you please explain?

**Comment by mskurnik** [comment]
> This should be OK for 8080 but won't work for port 80. I guess we'd want one in `piaware-web` for sdcard images too.

It should work on any port.

**Comment by eric1tran** [comment]
Please add `<link rel="icon" href="favicon.ico">` to index.html and I'll merge it in. I will add the favicon to piaware-web, which uses port 80 as @mutability pointed out.

**Pull request merged**
