### PR TITLE
Added UAS ADS-B category "B6" and generic UAS icon

### PR DESCRIPTION
**Pull request by Tissy**
Added UAS ADS-B category "B6" and generic UAS icon

### CODE REVIEW

**Comment by mutability** [comment]
Thanks! Not sure if we can directly take the icon as currently the skyaware icons are aligned with what FlightAware uses on the main website. Let me discuss it internally.

**Comment by Tissy** [comment]
Thank you for the reply.  I created this addition as I couldn't see the B6 category included in FlightAware nor the icon.  If it does already exist, that's great.  My feeder wasn't shows my UAS ADS-B on the main site, so again presumed it was filtering out the B6 category as it wasn't in the main code?

**Comment by mutability** [comment]
Emitter category doesn't affect the client side upload path. You can check what's being uploaded by running a second copy of `faup1090`

**Comment by Tissy** [comment]
> Not sure if we can directly take the icon as currently the skyaware icons are aligned with what FlightAware uses on the main website.
What UAS icon is used on the main site please as it would perhaps make sense to use that for consistency?

**Comment by Tissy** [comment]
> Thanks! Not sure if we can directly take the icon as currently the skyaware icons are aligned with what FlightAware uses on the main website. Let me discuss it internally.

What UAS icon is used on the main site please as it would perhaps make sense to use that for consistency?

**Comment by eric1tran** [comment]
Discussed with the WEB team and we currently do not have a UAS icon. Once we add one, we will add it to SkyAware.

**Pull request closed without merging**
