### PR TITLE
RTL-SDR bias tee

### PR DESCRIPTION
**Pull request by martian**
The rtl-sdr.com V3 dongle allows software control of the bias tee DC injection. This new option allows control of that feature.

### CODE REVIEW

**Comment by lunakato** [comment]
Good point about the old library versions. I hadn't expected versions so old to still be relevant but I support the aim for wide compatibility.

It might be possible to detect the presence of rtlsdr_set_bias_tee() at compile time but it's indirect. On the librtlsdr master branch, two changes were committed on the same day: rtlsdr_set_bias_tee() was introduced, and rtl-sdr.h stopped including rtl_tcp.h. Because dump1090 doesn't include rtl_tcp.h, __RTL_TCP_H will be defined for 0.6 but not for 0.7.
```
#define LIB_RTLSDR_VERSION_070_OR_UP !defined(__RTL_TCP_H)
#define RTLSDR_BIASTEE LIB_RTL_SDR_VERSION_070_OR_UP && !defined(NO_RTLSDR_BIASTEE)
```

For a cleaner solution, would you prefer this to be an optional feature?
If so, disabled or enabled by default?

**Comment by martian** [comment]
Good point about the old library versions. I hadn't expected versions so old to still be relevant but I support the aim for wide compatibility.

It might be possible to detect the presence of rtlsdr_set_bias_tee() at compile time but it's indirect. On the librtlsdr master branch, two changes were committed on the same day: rtlsdr_set_bias_tee() was introduced, and rtl-sdr.h stopped including rtl_tcp.h. Because dump1090 doesn't include rtl_tcp.h, __RTL_TCP_H will be defined for 0.6 but not for 0.7.
```
#define LIB_RTLSDR_VERSION_070_OR_UP !defined(__RTL_TCP_H)
#define RTLSDR_BIASTEE LIB_RTL_SDR_VERSION_070_OR_UP && !defined(NO_RTLSDR_BIASTEE)
```

For a cleaner solution, would you prefer this to be an optional feature?
If so, disabled or enabled by default?

**Comment by martian** [comment]
After discovering there are multiple librtlsdr sources, with different versioning, I've removed my previous mention of potential compile-time detection.

**Comment by mutability** [comment]
Yeah librtlsdr versioning is all a bit of a nightmare :(

I think doing it in the Makefile should be fine. For package builds we can embed the knowledge of what the corresponding Debian librtlsdr package supports in the rules file.

**Comment by martian** [comment]
merging a year's worth of commits from main made the feature branch a mess

**Pull request closed without merging**
