### PR TITLE
Control map via URL options

### PR DESCRIPTION
**Pull request by sigwx**
Update to allow things like http://pi:8080?hideSidebar=t&hideBanner=t&showTracks=t
to create a kiosk view of the map only, or http://pi:8080?hideMap=t to show only the aircraft table.

https://github.com/flightaware/dump1090/compare/master...sigwx:map_url_with_options#diff-3d873933c5a2f9e4d02b29aaf2cbfd6d

### CODE REVIEW

**Comment by sigwx** [comment]
Feature to allow URL arguments to control the initial map setup so as to have a sort of kiosk-style display that can be setup without using the keyboa.d

**Comment by sigwx** [comment]
Thanks.  The theory was that the options where with respect to how the map moves.  Since moving the center right shifts the map left, that was what I was going for.

**Comment by sigwx** [comment]
I believe I've updated to the latest dev and merged changes.  Did you want the up/down, left/right flipped or leave as they are :-)  thanks!

**Comment by eric1tran** [comment]
Maybe my brain sees it different :D Can you flip it? Thanks!

I'm looking into unifying this with #no_history url param we currently have.

**Comment by eric1tran** [comment]
Does each move "unit" equate to a distance?

**Comment by sigwx** [comment]
Flipped the behavior.   I didn't intend on units relating to a distance (i.e. if they do, it was luck not skill).  I was trying to find a value that had a reasonable impact on the display.

**Comment by mutability** [comment]
Have you considered just passing the lat/lon of the desired center?
(ditto for zoom, why not just specify the desired zoom level directly?)

**Comment by sigwx** [comment]
The theory was, I have the defaults set with the lat/lon of the antenna, and I just needed to move down the map (just like I would with the mouse) 20 or so pixels.  Likewise with the zoom, the default comes up great, just wanted to adjust them like I would from the display with the +/- zoom buttons.

**Comment by eric1tran** [comment]
I converted the #nohistory anchor tag to use query parameters and made the query parameter values a little more strict (i.e. check for 'True'). I think previously it would work when you set the parameter to anything. Also removed some "show" options. I think it'd make sense to just added the url options if you want to hide it and remove it if you want to show it.

**Comment by eric1tran** [comment]
enableRings() might be not working properly. You mind checking that?

**Comment by sigwx** [comment]
I wasn't sure if it would be possible for the things with 'show' would ever have the ability to be 'hidden' by default, if so, then show would be needed, but if they can't be hidden by default, show isn't necessary.
I'll give enableRings() a try and get back to you.

**Comment by sigwx** [comment]
I totally misread the toggleLayer()... enableRings() is updated now to actually enable the rings and update the checkbox now.

**Comment by eric1tran** [comment]
Thanks @sigwx. Going to give it another round of testing today and approve if it's all good

**Pull request merged**
