### PR TITLE
Add NetBSD detection to Makefile; use NetBSD's curses (simply called …

### PR DESCRIPTION
**Pull request by jvanwouw**
…curses) rather than ncurses on NetBSD. Tested on NetBSD 9.0 earmv6hf (Raspberry Pi B+). Thanks to https://mail-index.netbsd.org/tech-pkg/2000/08/03/0010.html I was originally able to get dump1090-fa compiling on NetBSD by hardcoding -lcurses. However, obviously it is better if NetBSD support is mainlined and that is why I decided to put in a little extra work to get autodetection/automation working.

### CODE REVIEW

**Comment by mutability** [comment]
The dev branch makefile has moved a bit and I don't have a netbsd install to test against - could you take a look at the conflicts?

**Comment by jvanwouw** [comment]
I have very little experience with Git, but is this not something git merge could take care of? I do not see any issues. Obviously I would need to test the new CPU_FEATURES code and the dev branch additions in general as I have only tested the master branch.

**Comment by mutability** [comment]
Yep, git merge will probably handle most of it, but I can't test the result.

Can you merge current dev into your PR branch, resolve conflicts & test, and push the results back to your PR branch?

**Comment by jvanwouw** [comment]
> Yep, git merge will probably handle most of it, but I can't test the result.
> 
> Can you merge current dev into your PR branch, resolve conflicts & test, and push the results back to your PR branch?

I have merged the dev branch with my local fork and pushed it to my GitHub fork. This is my first time doing this with Git, but I think it has worked. I have tested the dev branch on my Raspberry Pi B+ running NetBSD 9.0 (the interactive mode specifically, I have not been able to get the net mode working with the master branch, but that is probably a firewall issue as I have the RPi directly connected to my desktop) and it seems to be working well. In fact, I believe I am getting planes at a slightly lower RSSI with the dev branch and therefore achieving a greater range!

**Comment by mutability** [comment]
Merged, thanks!

(The dev branch does have some error-correction tweaks, so you may indeed be seeing a few more messages from that)

**Pull request merged**
