### PR TITLE
New converters

### PR DESCRIPTION
**Pull request by gtjoseph**

### CODE REVIEW

**Comment by mutability** [comment]
Can you keep the PRs to one thing at a time.
(The converter changes are probably ready to go; but I'm not ready to merge the cflags stuff as-is, and because those changes are now in a single PR, neither can be merged)

**Comment by gtjoseph** [comment]
Yeah, sorry about that.  Too many things going on right now.  I actually thought the cflags thing would be the easy one. :)
So do you want me to create separate branches off of airspy for them and future pull requests?  I _think_ there's a trick to base a pull request off another even though github doesn't really support it.   You may see some pull request noise as I try a few things.

**Comment by gtjoseph** [comment]
OK, just the converters now.

**Comment by mutability** [comment]
Not sure quite what happened but you ended up duplicating some commits from the dev branch; I'll prune those out before merging.

The cflags stuff I just need to think about some more. I don't like the replacement of `CFLAGS` with a different meaning halfway through the makefile; and I need to poke a bit at the conventions for `CFLAGS` elsewhere, because while I understand where you're coming from, it's not how it's usually done and I need to check that e.g. the Debian automation (which pushes hardening flags into CFLAGS, IIRC) doesn't break.

**Comment by mutability** [comment]
Pruned & merged. I removed the dead prototypes, add them back when needed. I did _not_ commit the regenerated starch files for now to try to minimize your conflicts. When you're happy with where the starch stuff is at, I can update the generated files - for now just remember to do a `make starchgen` after checkout.

nb: I am mostly out until after CNY now.

**Comment by gtjoseph** [comment]
>Not sure quite what happened but you ended up duplicating some commits from the dev branch; I'll prune those out before merging.

Oy.  Sorry about that.  I work with Gerrit all day so I'm used to being able to just create a review based off other review without having to worry about what else was in a branch.  Working directly with GitHub makes me feel like I've got a hand tied behind my back. :)  I'll try and be more careful.

>  it's not how it's usually done 

That's how autoconf works when you run ./configure.  Any CFLAGS passed on the command line are appended to the internal ones.  We could just name it EXTRA_CFLAGS and append it to CFLAGS after the SDR and starch stuff.  Was quite handy for specifying `-Wno- ` flags to get by compiler warnings-as-errors.

> I am mostly out until after CNY now

Happy New Year and thanks for all your work!

**Pull request closed without merging**
