### PR TITLE
Make more functions static

### PR DESCRIPTION
**Pull request by neheb**
This should result in a smaller size.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Switched to dev branch.

**Comment by mutability** [comment]
These changes seem reasonable warnings or no, but why "a smaller size"?

**Comment by neheb** [comment]
static allows the linker to work more efficiently as inline is implicit.

**Comment by mutability** [comment]
I guess that you mean that the compiler/linker is free to omit the standalone version of a `static` function that is only ever inlined?

If you are compiling for space, inlining can actually be counterproductive (if it's done more than once, anyway)

**Comment by neheb** [comment]
Eh no. The compiler is free to inline static functions implicitly. Not so with normal functions.

**Comment by mutability** [comment]
Eh? The compiler can and will inline both static and non-static functions if a definition is available.
The difference is whether it is also required to emit a non-inline version.

I guess I don't understand what this change is trying to achieve; do you have some before-and-after size numbers?

**Comment by mutability** [comment]
Here is an example:

```
#include <stdio.h>

int nonstatic_version() {
    return 42;
}

static int static_version() {
    return 42;
}

int main(int argc, char **argv)
{
    printf("nonstatic = %d\n", nonstatic_version());
    printf("static = %d\n", static_version());
    return 0;
}
```

```
$ gcc -Wall -O3 -c -o static_thing.o static_thing.c
```

```
$ objdump -d -r static_thing.o

static_thing.o:     file format elf64-x86-64


Disassembly of section .text:

0000000000000000 <nonstatic_version>:
   0:	b8 2a 00 00 00       	mov    $0x2a,%eax
   5:	c3                   	retq   

Disassembly of section .text.startup:

0000000000000000 <main>:
   0:	48 8d 35 00 00 00 00 	lea    0x0(%rip),%rsi        # 7 <main+0x7>
			3: R_X86_64_PC32	.LC0-0x4
   7:	48 83 ec 08          	sub    $0x8,%rsp
   b:	ba 2a 00 00 00       	mov    $0x2a,%edx
  10:	bf 01 00 00 00       	mov    $0x1,%edi
  15:	31 c0                	xor    %eax,%eax
  17:	e8 00 00 00 00       	callq  1c <main+0x1c>
			18: R_X86_64_PLT32	__printf_chk-0x4
  1c:	48 8d 35 00 00 00 00 	lea    0x0(%rip),%rsi        # 23 <main+0x23>
			1f: R_X86_64_PC32	.LC1-0x4
  23:	ba 2a 00 00 00       	mov    $0x2a,%edx
  28:	bf 01 00 00 00       	mov    $0x1,%edi
  2d:	31 c0                	xor    %eax,%eax
  2f:	e8 00 00 00 00       	callq  34 <main+0x34>
			30: R_X86_64_PLT32	__printf_chk-0x4
  34:	31 c0                	xor    %eax,%eax
  36:	48 83 c4 08          	add    $0x8,%rsp
  3a:	c3                   	retq   

```

note how the compiler has inlined both calls;
and it has emitted a separate version for the non-static version only.

If I link that into a full binary, `nonstatic_version` is discarded by the linker and is not included in the final binary.

**Comment by neheb** [comment]
In any case, it's worthwhile to fix.

**Pull request merged**
