### PR TITLE
Improvement of correlation functions and preamble check, merge back from fork

### PR DESCRIPTION
**Pull request by wiedehopf**
For more detailed commit history and evolving of these changes see https://github.com/wiedehopf/readsb

### CODE REVIEW

**Comment by wiedehopf** [comment]
before:
```
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  4588436 Mode-S message preambles received
    2791391 with bad message format or invalid CRC
    1637745 with unrecognized ICAO address
    159300 accepted with correct CRC
  -7.1 dBFS mean signal power
  -0.8 dBFS peak signal power
  19869 messages with signal power above -3dBFS
159300 total usable messages
724 surface position messages received
20955 airborne position messages received
20523 global CPR attempts with valid positions

  14328 ms for demodulation

```
after:
```
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  2637242 Mode-S message preambles received
    1287932 with bad message format or invalid CRC
    1185594 with unrecognized ICAO address
    163716 accepted with correct CRC
  -7.1 dBFS mean signal power
  -0.8 dBFS peak signal power
  21304 messages with signal power above -3dBFS
163716 total usable messages
722 surface position messages received
21530 airborne position messages received
  11932 ms for demodulation
```

This is on an x86_64 box but my tests on readsb on the pi3 show that the CPU load should reduce compared to the state before this PR.

I'm getting different (quite a bit better) numbers from readsb ... not really sure why, it's the same sample after all.
But i'm not too keen to investigate that as the forks have diverged quite a bit.
Maybe differences in the stat keeping? No clue.
Different number with DF11 handling or something like that i would have expected but CPR handling being off by 10 % seems strange.

readsb numbers with same preamble threshold and sample:
```
  710934528 samples processed
  0 samples dropped
  0 Mode A/C messages received
  2631568 Mode-S message preambles received
    1278484 with bad message format or invalid CRC
    1183328 with unrecognized ICAO address
    161017 accepted with correct CRC
    8739 accepted with 1-bit error repaired
  -7.2 dBFS mean signal power
  -0.8 dBFS peak signal power
  21972 messages with signal power above -3dBFS

 Phase stats
         3        4        5        6        7
   3549492  3549492  3470244  3470244  2882252
         4        5        6        7        8
     32063    33054    33835    34915    35889

169756 total usable messages
752 surface position messages received
23365 airborne position messages received
  12998 ms for demodulation
```

**Comment by mutability** [comment]
Thanks for putting this together! I probably won't take it wholesale but I will test it out and see what I can take.

At a glance I'd guess the readsb difference is a difference in the `--fix` setting? (No error-corrected messages seen in the dump1090-fa stats)

**Comment by mutability** [comment]
(any chance you can make your test file available somewhere so we're working from the same thing?)

**Comment by wiedehopf** [comment]
Thought --fix was implicit, my mistake.
Give me a moment for an URL so i can share the samples i used.

If you have a good sample, maybe even a composite of multiple receivers i'd be happy to run that as well.

If you really want to get into testing exactly you might want to do the mstime() hack i used it allows me to get the CPR decoding right without --throttle and thus i can get better numbers (valid positions is a pretty solid indicator due to CRC and the speed check)

**Comment by wiedehopf** [comment]
Command line this time with location for range check and --fix
```
./dump1090 --device-type ifile --ifile lax.dat --quiet --stats --fix --throttle --lat 33 --lon -118
```
Before patches:
```
Statistics: Mon Jan  4 16:54:29 2021 CET - Mon Jan  4 16:59:25 2021 CET
Local receiver:
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  4576491 Mode-S message preambles received
    2778181 with bad message format or invalid CRC
    1632862 with unrecognized ICAO address
    159135 accepted with correct CRC
    6313 accepted with 1-bit error repaired
  -7.2 dBFS mean signal power
  -0.7 dBFS peak signal power
  20493 messages with signal power above -3dBFS
165448 total usable messages
740 surface position messages received
22805 airborne position messages received
23093 global CPR attempts with valid positions
0 global CPR attempts with bad data
  0 global CPR attempts that failed the range check
  0 global CPR attempts that failed the speed check
15 global CPR attempts with insufficient data
285 local CPR attempts with valid positions
  0 aircraft-relative positions
  0 receiver-relative positions
167 local CPR attempts that did not produce useful positions
  120 local CPR attempts that failed the range check
  0 local CPR attempts that failed the speed check
0 CPR messages that look like transponder failures filtered
0 non-ES altitude messages from ES-equipped aircraft ignored
167 unique aircraft tracks
18 aircraft tracks where only one message was seen
28 aircraft tracks which were not marked reliable
CPU load: 5.5%
  13785 ms for demodulation
  2434 ms for reading from USB
  36 ms for network input and background tasks
```
After patches:
```
Statistics: Mon Jan  4 16:54:53 2021 CET - Mon Jan  4 16:59:49 2021 CET
Local receiver:
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  2631568 Mode-S message preambles received
    1278484 with bad message format or invalid CRC
    1183328 with unrecognized ICAO address
    161017 accepted with correct CRC
    8739 accepted with 1-bit error repaired
  -7.2 dBFS mean signal power
  -0.8 dBFS peak signal power
  21972 messages with signal power above -3dBFS
169756 total usable messages
743 surface position messages received
23352 airborne position messages received
23629 global CPR attempts with valid positions
0 global CPR attempts with bad data
  0 global CPR attempts that failed the range check
  0 global CPR attempts that failed the speed check
13 global CPR attempts with insufficient data
295 local CPR attempts with valid positions
  0 aircraft-relative positions
  0 receiver-relative positions
171 local CPR attempts that did not produce useful positions
  126 local CPR attempts that failed the range check
  0 local CPR attempts that failed the speed check
0 CPR messages that look like transponder failures filtered
0 non-ES altitude messages from ES-equipped aircraft ignored
165 unique aircraft tracks
15 aircraft tracks where only one message was seen
25 aircraft tracks which were not marked reliable
CPU load: 4.9%
  11677 ms for demodulation
  2666 ms for reading from USB
  41 ms for network input and background tasks
```

CPU time is reduced on a pi3 as well, don't have a pi zero to test.
That's a big plus in valid positions and messages.

Just for reference the readsb version i'm running now pretty much in line with the stats from dump1090-fa:
```
Local receiver:
  710934528 samples processed
  0 samples dropped
  0 Mode A/C messages received
  2631568 Mode-S message preambles received
    1278484 with bad message format or invalid CRC
    1183328 with unrecognized ICAO address
    161017 accepted with correct CRC
    8739 accepted with 1-bit error repaired
  -7.2 dBFS mean signal power
  -0.8 dBFS peak signal power
  21972 messages with signal power above -3dBFS

 Phase stats
         3        4        5        6        7
   3549492  3549492  3470244  3470244  2882252
         4        5        6        7        8
     32063    33054    33835    34915    35889

169756 total usable messages
752 surface position messages received
23365 airborne position messages received
23638 global CPR attempts with valid positions
0 global CPR attempts with bad data
  0 global CPR attempts that failed the range check
  21 global CPR attempts that failed the speed check
13 global CPR attempts with insufficient data
294 local CPR attempts with valid positions
  247 aircraft-relative positions
  47 receiver-relative positions
164 local CPR attempts that did not produce useful positions
  118 local CPR attempts that failed the range check
  0 local CPR attempts that failed the speed check
0 CPR messages that look like transponder failures filtered
0 non-ES altitude messages from ES-equipped aircraft ignored
152 unique aircraft tracks
0 aircraft tracks where only one message was seen
CPU load: 5.1%
  12650 ms for demodulation
  2566 ms for reading from USB
  11 ms for network input and background tasks
```

**Comment by wiedehopf** [comment]
So i was curious about the sample processed count being off.

```
root@box # du -b lax.dat
1421869056 lax.dat

>>> 1421869056/2
710934528.0
```

```
Local receiver:
  710934528 samples processed
```
So that all agrees.
Seems your fifo is somehow inflating the count of processes samples?

As to taking it wholesale ... i suppose i can split out the refactoring with slice_byte from the actual preamble changes.
The refactoring shouldn't be an issue to just take as it doesn't really change anything.
The first commit is completely independent anyhow.

**Comment by mutability** [comment]
Yeah stats are double-counting the overlap region at the moment

**Comment by wiedehopf** [comment]
Comparing just the slice_phase changes:
```

Statistics: Mon Jan  4 20:06:09 2021 CET - Mon Jan  4 20:11:06 2021 CET
Local receiver:
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  4588436 Mode-S message preambles received
    2791391 with bad message format or invalid CRC
    1637745 with unrecognized ICAO address
    159300 accepted with correct CRC
  -7.1 dBFS mean signal power
  -0.8 dBFS peak signal power
  19869 messages with signal power above -3dBFS
159300 total usable messages
724 surface position messages received
20955 airborne position messages received
20523 global CPR attempts with valid positions
0 global CPR attempts with bad data
  0 global CPR attempts that failed the range check
  0 global CPR attempts that failed the speed check
685 global CPR attempts with insufficient data
262 local CPR attempts with valid positions
  0 aircraft-relative positions
  0 receiver-relative positions
894 local CPR attempts that did not produce useful positions
  0 local CPR attempts that failed the range check
  0 local CPR attempts that failed the speed check
0 CPR messages that look like transponder failures filtered
0 non-ES altitude messages from ES-equipped aircraft ignored
155 unique aircraft tracks
8 aircraft tracks where only one message was seen
19 aircraft tracks which were not marked reliable
CPU load: 10.4%
  19559 ms for demodulation
  11030 ms for reading from USB
  222 ms for network input and background tasks


Statistics: Mon Jan  4 20:17:47 2021 CET - Mon Jan  4 20:22:43 2021 CET
Local receiver:
  712703078 samples processed
  0 samples dropped
  0 Mode A/C messages received
  4587491 Mode-S message preambles received
    2759293 with bad message format or invalid CRC
    1667828 with unrecognized ICAO address
    160370 accepted with correct CRC
  -7.1 dBFS mean signal power
  -0.8 dBFS peak signal power
  20142 messages with signal power above -3dBFS
160370 total usable messages
722 surface position messages received
21135 airborne position messages received
20698 global CPR attempts with valid positions
0 global CPR attempts with bad data
  0 global CPR attempts that failed the range check
  0 global CPR attempts that failed the speed check
683 global CPR attempts with insufficient data
261 local CPR attempts with valid positions
  0 aircraft-relative positions
  0 receiver-relative positions
898 local CPR attempts that did not produce useful positions
  0 local CPR attempts that failed the range check
  0 local CPR attempts that failed the speed check
0 CPR messages that look like transponder failures filtered
0 non-ES altitude messages from ES-equipped aircraft ignored
156 unique aircraft tracks
10 aircraft tracks where only one message was seen
19 aircraft tracks which were not marked reliable
CPU load: 11.1%
  20644 ms for demodulation
  12162 ms for reading from USB
  204 ms for network input and background tasks
```

**Comment by wiedehopf** [comment]
Tested all the commits with this command:
```
/dump1090 --device-type ifile --ifile lax.dat --quiet --stats --throttle --lat 33 --lon -118 2>&1 >> compare.log
```
Log is available here: https://pastebin.com/3inZ4HQr

Sorry for the force push if you'd rather i can open a new PR.
Anyhow it doesn't really matter if you don't want the whole PR but rather only apply whatever you like ;)

**Comment by wiedehopf** [comment]
Seems i made a semantic change in regards to the preamble statistics which wasn't intended.
Going to force push the amended commits in a moment.

**Comment by wiedehopf** [comment]
Running this script on the pi3b+ right now (you'd have to change the branch name from dev2 to whatever you are using.
```
#!/bin/bash

output=compare.log
rm -f $output
for N in {6..0}; do
	git checkout -f dev2~$N >> $output
	make
	./dump1090 --device-type ifile --ifile lax.dat --quiet --stats --throttle --lat 33 --lon -118 >> $output 2>&1
	echo >> $output
	echo ----------------------------------- >> $output
done
```

That with the fix to the preamble counting should provide a good comparison of what is different.
Though the number of preambles detected isn't quite comparable to before because it's not always all 5 phases that we score.

Will post a pastebin of the new run when it's done.

**Comment by wiedehopf** [comment]
https://pastebin.com/EqdRjh3L

i'll re-run the last 2 commits.
the ((always_inline)) ... surprising it changes something but it does apparently.

**Comment by wiedehopf** [comment]
Ok seems like the last patch isn't necessary (at least on the pi, maybe on x86 it behaves differently)
```
HEAD is now at 1806c6f demod2400: move phase scoreing and best variable updating into score_phase()
  19929 ms for demodulation
  20316 ms for demodulation
  19908 ms for demodulation
HEAD is now at f0a891c don't unnecessarily call scoremodesmessage
  19562 ms for demodulation
  19912 ms for demodulation
  20332 ms for demodulation
HEAD is now at 91e9321 change preamble detection to a modified approach
  18970 ms for demodulation
  18994 ms for demodulation
  18821 ms for demodulation
HEAD is now at cd28f66 ((always_inline) the slice_phase functions
  18813 ms for demodulation
  19504 ms for demodulation
  18980 ms for demodulation
```

I should probably have no other load to reduce the run to run variance.

**Comment by wiedehopf** [comment]
So to test the last patch that forces inlining i made a run of 20 with the sample file residing in /run (shorter run time due to less memory than disk).
Average before the patch 7083 ms, average after the patch 7074.55.
I'd call that no change :)

Now the improvement in the number of detected positions is quite clear and the patch series also decreases CPU load slightly, for the LHR sample even more.
If you don't like the number preamble detections i'd suggest you just up the threshold, it's currently just set at 75
```
272         ref_level = base_noise * 75;
```
You can set it however you please for my fork i've got it configurable.
I've done some minor tweaking to even out the number of preamble detection between phases (i have some stats for the different phase decodes as well as preamble detections not included in this PR).
If you're interested in those really minor tweaks: https://github.com/wiedehopf/readsb/commit/e610c2767b9c1563c082b7ebc419d147e750023c
They don't change much at all but they don't increase cycles besides the threshold change but i'm choosing a bit higher CPU usage for my fork and automatically reduce it only one processor is detected.

Have fun with the testing :)

**Pull request closed without merging**
