### PR TITLE
Pi cpu temp monitor

### PR DESCRIPTION
**Pull request by byronbest**
With the help of a cron job (get_cpu_temp.sh) copies current CPU temp so it can be passed to the client for display and monitoring.
I have a pi outside attached to the antenna, and this allows me to monitor it remotely.

### CODE REVIEW

**Comment by danmilon** [comment]
I don't think this feature belongs to dump1090. It's out of scope and opens a can of worms if we start showing resource usage information. (support for different hosts, etc).

There are better ways to do that outside dump1090. e.g. I use [rpi-monitor](https://rpi-experiences.blogspot.com/p/rpi-monitor.html) and there's also a nice [docker image](https://github.com/michaelmiklis/docker-rpi-monitor) for it.

**Comment by byronbest** [comment]
Very nice to hear from you.

I'm using piaware, so thought it was useful in that context, all on the
same display. A branch from my pull #51, fixing the infobox.

I realize it's kinda lame, and your points are well taken. Not pursuing
anything like pimonitor, nor other hardware. I've been switching to ssh to
check, and wrapped it up to share as a small addition to your code.

Best,
Byron.

**Comment by byronbest** [comment]
RPi-monitor sadly does not update the temperature, unless I shift-reload (it has cached all the displayed values).

In fact has a warning in the console: [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Looks nice, tho

**Comment by mutability** [comment]
Yeah, this doesn't belong in dump1090; there are a bunch of existing resource / system monitoring tools around which are actually designed for this.

**Comment by byronbest** [comment]
Oh yeah, RPi-monitor has Options page to enable refreshing status!
Would be nice to optionally turn off some of the info; it doesn't fit on my tiny piaware screen. (9 inch tablet)

**Pull request closed without merging**
