### PR TITLE
CSS updates (including dark mode)

### PR DESCRIPTION
**Pull request by egid**
Hi! Please forgive me if this is too much at once and/or if I'm inadvertently wrecking IE11 support or something. 

This PR includes a few different changes, and if it's preferred, I can break it up further.

1. CSS vars, and in turn support for OS-native dark mode toggling. Screenshots at the end.
2. ~~Standardized the close button styles between the column picker and the settings panel.~~ -- skipping this for now
3. Ran a Prettier pass against `style.css` -- most changes are tabs → 4 spaces, but it also broke out a lot of single-line rules that had multiple properties per line. This makes the file a few lines longer, but much more readable.

Again, apologies if I'm doing too much in one go, or if these changes are no bueno — I haven't submitted to the project before.

### CODE REVIEW

**Comment by eric1tran** [comment]
Awesome. Will have to get some WEB folks to review. Have you tested it on different browsers?

**Comment by egid** [comment]
I did my initial testing in Safari and Firefox, but I *just* realized I was doing my testing in public_html against the deprecated version — I'm new to this codebase!

I'm gonna take a few days to take another pass at this and update the PR, unless y'all would prefer a fresh one.

**Comment by egid** [comment]
Ok, initial pass for the modern UI is in and the commits are broken up a lot more sanely. I'll rip out my previous work in a few. In the meantime, here's the UI in Chrome and Firefox:

## Firefox 89
Screen Shot 2021-05-22 at 11 33 58 Screen Shot 2021-05-22 at 11 33 36

Screen Shot 2021-05-22 at 11 37 53 Screen Shot 2021-05-22 at 11 37 41 


## Chrome 90
Screen Shot 2021-05-22 at 11 36 00 Screen Shot 2021-05-22 at 11 35 01 

Screen Shot 2021-05-22 at 11 36 55 Screen Shot 2021-05-22 at 11 37 11

**Comment by egid** [comment]
Oh, meant to ask -- is there a specific supported browser/version list I should be testing against? 

I saw a bunch of comments referring to the older ui being reserved for ie11, so I skipped it and deliberately tested in blink/gecko. Things look good in WebKit as well.

**Comment by eric1tran** [comment]
Apologies for the delay @egid, been busy with other things for our next release. Just tried this out on Chrome 91 and the text in the aircraft table/info pane is difficult to see in dark mode. Are you seeing this as well?

image

**Comment by egid** [comment]
I'll take another look! Probably missed something while testing.

**Comment by chadhutchins182** [comment]
@eric1tran were fixes made to the aircraft table that you noted or did it get better with a newer version of Chrome?

**Comment by eric1tran** [comment]
No I must've accidentally merged it while testing, thanks for catching that

**Pull request merged**
