### PR TITLE
Added macOS build capability

### PR DESCRIPTION
**Pull request by elvis-epx**

### CODE REVIEW

**Comment by bbss** [comment]
Thanks, got this to work thanks to the branch+tips but ran into a little more trouble.

Had to follow instructions here:
https://github.com/Nuand/bladeRF/wiki/Getting-started%3A-Mac-OSX

Added the directory `PKG_CONFIG_PATH=/opt/local/lib/pkgconfig/` before the make.

Added the snippet of @mylesagray 

But still ran into trouble `make`-ing dump1090, I think it's because my gcc is 4.2.x and got a type error which actually was only a warning. Removing the -Werror flag in the Makefile made the build succeed.

```
-CFLAGS += $(DIALECT) -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE
+CFLAGS += $(DIALECT) -O2 -g -Wall -W -D_DEFAULT_SOURCE
```

Then I ran into an issue when trying to run the dump1090 binary with the blade lib not being available, had to:
```
otool -L dump1090
;;change the @rpath path:
dump1090:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/local/opt/librtlsdr/lib/librtlsdr.0.dylib (compatibility version 0.0.0, current version 0.6.0)
	/usr/local/opt/libusb/lib/libusb-1.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
	@rpath/libbladeRF.2.dylib (compatibility version 2.0.0, current version 0.0.0)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)

;;by using install_name_tool
install_name_tool -change @rpath/libbladeRF.2.dylib /opt/local/lib/libbladeRF.2.dylib dump1090
```

After that running dump1090 works for me!

**Comment by mikeage** [comment]
Running without bladerf (`make BLADERF=no DARWIN=yes`) worked perfectly for me with no extra steps. Nice work!

**Comment by mikenor** [comment]
I think this is not a very good way of doing it. Dump1090 does not need MacOS support "added" per se - it already has it. But it's apparently been neglected and fallen into disrepair.

Having a compile-time parameter `DARWIN=yes` seems inelegant, as that ought to be automatically detectable. Dump1090's Makefile used to automatically detect Darwin or Linux but that was removed by commit bef563b8a32862e1c487b4e6678384ea8175dc04. It would probably be doable to bring back.

And Dump1090 already has code in the `compat/` folder that implements the timing functions needed for MacOS compatibility. Rather than just throwing in a different implementation from a third party, it might be worth getting the existing code working again. My understanding is that newer versions of MacOS do provide "some" of the functionality, so the compat code probably needs to be updated to not duplicate those functions on newer OS versions.

I tried building the last commit prior to the Makefile being clobbered but my MacOS is too new. It barfs about `compat/clock_nanosleep.h` redefining stuff that's already defined in 10.14's header files. I don't think it would take much to fix.

**Comment by mikenor** [comment]
Fyi I opened pull request #38 which fixes Mac compatibility by using the already-existing compatibility code.

**Pull request closed without merging**
