### PR TITLE
fix: change calloc parameter order

### PR DESCRIPTION
**Pull request by Swiftyhu**
Relevant forum post: https://forums.fedoraforum.org/showthread.php?331882-Latest-gcc-compiler

### CODE REVIEW

**Comment by kzyapkov** [comment]
This currently breaks the build of https://aur.archlinux.org/packages/dump1090-fa-git

**Comment by mutability** [comment]
It's splitting hairs, but if recent gcc is going to complain then okay.

(AFAIK, swapping parameter order to calloc makes _no_ functional difference -- `calloc(x,y)` returns at least `x*y` zeroed bytes, with alignment suitable for any type)

**Comment by calimeroteknik** [comment]
Will this get merged into the master branch as well?

**Comment by mutability** [comment]
Yes, when we next do a release.

**Pull request merged**
