### PR TITLE
Load lighttpd alias module before using alias.url

### PR DESCRIPTION
**Pull request by flyingstar16**
On some instances of lighttpd, like the one that comes with PiHole, the
alias module is not loaded by default. This makes the configuration of
PiAware's lighttpd not work (see e.g.
https://discourse.pi-hole.net/t/pi-hole-and-piaware-lighttpd/9611).

This way we ensure that the alias module is loaded even on non-default
lighttpd configurations.

### CODE REVIEW

**Comment by mutability** [comment]
Is lighttpd happy about loading the module twice? Iirc it complains about
that in other cases.

**Comment by flyingstar16** [comment]
It didn't complain when I tried, by adding it twice in two different files.
I also tried to load it into `lighttpd.conf`, in the default `server.modules = ([...])` statements - as opposed to `server.modules += ( "mod_alias" )` and again, `lighttpd -t -f lighttpd.conf` told me "Syntax OK" and lighttpd restarted, and worked, without an issue. No errors are shown in the logs upon restarting.

I checked if I could use the if statements, but `modules` are not one of the supported fields you can check (see [lighttpd Docs_Configuration](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_Configuration)).

**HOWEVER**

You are correct: default versions of lighttpd will complain about it.
See [lighttpd/src/plugins.c](https://github.com/lighttpd/lighttpd1.4/blob/d4b726bf24b8a8907c0e5845e90c6edf760d4e3c/src/plugin.c#L145)

I don't know why Debian is different, but I'll turn this into a commented option, with an explanation as to why you might need to enable it.

**Comment by flyingstar16** [comment]
Hi, is there any other changes you think I should make here?
Thanks!

**Comment by mutability** [comment]
Sorry for the delay; I need to find some time to look at this properly, but I haven't forgotten about it.

**Comment by mutability** [comment]
I wish we could be smarter about this but lighttpd does not make that very easy..

**Comment by flyingstar16** [comment]
My turn to reply very late - thanks for the merge, I saw it come in during one of the latest updates :)

I also installed both Pi-Hole and PiAware on a Pi in another location and it made it really easy to make it work (I can neither confirm nor deny whether it took my own commit to remind me how to make SkyView work :/ )

**Pull request merged**
