### PR TITLE
Replace ftime() with gettimeofday()

### PR DESCRIPTION
**Pull request by WIZARDISHUNGRY**

### CODE REVIEW

**Comment by bovine** [comment]
What is the reasoning for changing to gettimeofday()?

Also, there are conflicts in this request that need to be resolved first.

**Comment by mutability** [comment]
Can you send pull requests to the upstream repository at mutability/dump1090, as that's what the next iteration of the Flightaware version of dump1090 will be based on.

(also, if you're trying to build on OS X, upstream builds on OS X via travis so it's more likely to work out of the box)

**Comment by WIZARDISHUNGRY** [comment]
Deprecated by POSIX in 2008. It doesn't exist on OpenBSD (and supposedly others) so it breaks compilation. I'll fix the merge.

**Comment by WIZARDISHUNGRY** [comment]
@mutability looks like using clock_gettime has made this patch irrelevant. I'll base any development off your branch from now on.

**Pull request closed without merging**
